#ifndef COURSE_PROJECT_ALLOCATOR_TYPES_H
#define COURSE_PROJECT_ALLOCATOR_TYPES_H

enum allocator_types
{
    GLOBAL_HEAP,
    SORTED_LIST,
    BUDDIE_SYSTEM,
    BOUNDARY_TAGS
};

#endif //COURSE_PROJECT_ALLOCATOR_TYPES_H
